In [1]:
import torch

In [2]:
x = torch.Tensor([2,5])
y = torch.Tensor([5,1])

z = x * y 


In [3]:
z

tensor([10.,  5.])

In [7]:
x = torch.reshape(x, [2,1])

In [8]:
x

tensor([[2.],
        [5.]])

In [9]:
x =torch.zeros(5,3)

In [10]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
y=torch.zeros([5,3])

In [14]:
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
y = torch.rand([3,6])

In [18]:
y

tensor([[0.4239, 0.9586, 0.2327, 0.1883, 0.5050, 0.9883],
        [0.6270, 0.3928, 0.7159, 0.0764, 0.7335, 0.8432],
        [0.4938, 0.5510, 0.0782, 0.0514, 0.0475, 0.4785]])

In [25]:
 y = y.view(1,18)

In [26]:
y

tensor([[0.4239, 0.9586, 0.2327, 0.1883, 0.5050, 0.9883, 0.6270, 0.3928, 0.7159,
         0.0764, 0.7335, 0.8432, 0.4938, 0.5510, 0.0782, 0.0514, 0.0475, 0.4785]])