In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
# sentenses
sent = ['Glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am a good boy',
        'i am a good devloper',
        'understand the meaning of words',
        'your vidoes are good']

In [6]:
sent

['Glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good devloper',
 'understand the meaning of words',
 'your vidoes are good']

In [7]:
# vocabulary size
voc_size = 100

In [8]:
# one hot encoding
onehot = [one_hot(word,voc_size)for word in sent]

In [9]:
onehot

[[90, 50, 43],
 [16, 90, 50, 3],
 [16, 96, 50, 40],
 [45, 51, 18, 48, 89],
 [45, 51, 18, 48, 68],
 [36, 16, 86, 50, 9],
 [53, 7, 50, 48]]

# word embedding representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # pad_sequences is for when we have to go for embedding layers ALL THE SENTENSES SHOULD BE IN SAME LENGTH
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(onehot,padding='pre',maxlen=sent_length) # padding='pre means we have 4 words on our sentence but our mmaxlen we set 8 so to trsnsform it.it puts 4 zeros before the vectoer and 
# padding='post all the remaing words after the that one hot vectoer

In [14]:
embedded_docs

array([[ 0,  0,  0,  0,  0, 90, 50, 43],
       [ 0,  0,  0,  0, 16, 90, 50,  3],
       [ 0,  0,  0,  0, 16, 96, 50, 40],
       [ 0,  0,  0, 45, 51, 18, 48, 89],
       [ 0,  0,  0, 45, 51, 18, 48, 68],
       [ 0,  0,  0, 36, 16, 86, 50,  9],
       [ 0,  0,  0,  0, 53,  7, 50, 48]])

In [15]:
dim = 10

# Embedding layer

In [17]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length= sent_length))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             1000      
Total params: 1,000
Trainable params: 1,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

array([[[ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
          4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
         -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
          3.42894457e-02],
        [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
          4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
         -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
          3.42894457e-02],
        [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
          4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
         -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
          3.42894457e-02],
        [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
          4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
         -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
          3.42894457e-02],
        [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
          4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
         -2.62477286e-02, -3.89230475e-02, -3.189329

In [20]:
embedded_docs[0]

array([ 0,  0,  0,  0,  0, 90, 50, 43])

In [23]:
model.predict(embedded_docs)[0]

array([[ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
         4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
        -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
         3.42894457e-02],
       [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
         4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
        -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
         3.42894457e-02],
       [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
         4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
        -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
         3.42894457e-02],
       [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
         4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
        -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
         3.42894457e-02],
       [ 3.51422466e-02,  3.42607498e-04, -4.71982472e-02,
         4.03931625e-02, -1.37731321e-02, -3.03949006e-02,
        -2.62477286e-02, -3.89230475e-02, -3.18932906e-02,
         3.

In [24]:
import pytorch

ModuleNotFoundError: No module named 'pytorch'

In [25]:
!pip install pytorch

  Failed building wheel for pytorch
Command "C:\Users\HP\Anaconda3\envs\untitled\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-qcszy362\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HP\AppData\Local\Temp\pip-record-cua3w350\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HP\AppData\Local\Temp\pip-install-qcszy362\pytorch\
You are using pip version 10.0.1, however version 20.2b1 is available.

  Running setup.py bdist_wheel for pytorch: started
  Running setup.py bdist_wheel for pytorch: finished with status 'error'
  Complete output from command C:\Users\HP\Anaconda3\envs\untitled\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-qcszy362\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\HP\AppData\Local\Temp\pip-wheel-dh8qiu5a --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\HP\AppData\Local\Temp\pip-install-qcszy362\pytorch\setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  
  ----------------------------------------
  Running setup.py clean for pytorch
Failed to build pytorch
  Running setup.py install for pytorch: started
    Runni


You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [26]:
!python -m pip install --upgrade pip

Requirement already up-to-date: pip in c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages (20.1.1)


In [ ]:
!conda install pytorch torchvision cudatoolkit=10.2 -c pytorch